version: '3'
services:
    nginx1.16:
        image: nginx1.16-centos7
        network_mode: "host"
        container_name: "nginx1.16"
        ports:
          - "80:80"
          - "90:90"
          - "443:443"
          - "8080:8080"
        volumes:
          - /var/www:/var/www/
          - /var/log/nginx/:/var/log/nginx/
          - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
          - /etc/nginx/conf.d/:/etc/nginx/conf.d/:ro
        command: ./entrypoint.sh
    php72:
        image: php72-centos7
        network_mode: "host"
        container_name: "php72"
        ports:
          - "9000:9000"
        volumes:
          - /etc/php.int:/etc/php.int:ro
          - /etc/php.d/:/etc/php.d/:ro
          - /etc/php-fpm.conf:/etc/php-fpm.conf:ro
          - /etc/php-fpm.d/:/etc/php-fpm.d/:ro
          - /var/log/php-fpm/:/var/log/php-fpm/
          - /var/www/:/var/www/
        command: ./entrypoint.sh
    redis5:
        image: redis5-centos7
        network_mode: "host"
        container_name: "redis5"
        ports:
          - "6379:6379"
          - "6380:6380"
        volumes:
          - /etc/redis/:/etc/redis/:ro
          - /var/log/redis/:/var/log/redis/
        command: ./entrypoint.sh
    mysql8:
        image: mysql8-mini-centos7
        network_mode: "host"
        container_name: "mysql8"
        ports:
          - "3306:3306"
        volumes:
          - /var/log/mysqld.log:/var/log/mysqld.log
        command: ./entrypoint.sh
