version: '3'
services:
    nginx1.16:
        image: juan083/nginx1.16-centos7
        container_name: "nginx1.16"
        ports:
          - "80:80"
          - "90:90"
          - "443:443"
          - "8080:8080"
        volumes:
          - /var/www:/var/www/
          - /var/log/nginx/:/var/log/nginx/
          - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
          - /etc/nginx/conf.d/:/etc/nginx/conf.d/:ro
        command: ./entrypoint.sh
