version: '3'
services:
  nginx116:
    image: nginx116
    tty: true
    network_mode: "host"
    container_name: "nginx116"
    ports:
      - "80:80"
      - "90:90"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/www:/var/www:rw
      - /var/log/nginx/:/var/log/nginx:rw
      - /etc/nginx/:/var/nginx/:rw
    restart: always
    command: nginx -g "daemon off;"
